---
title: "Evans Copy"
format: html
Authors: "Evan Whitfield, Ryan Friedman, Ralph Church"
---

Loading any libraries needed.
```{r}
library(tidyverse)
library(readr)
library(dplyr)
library(lubridate)
library(tidymodels)
library(broom)
```

Reading in the data.
```{r}
bike_data <- read_csv("../Data/SeoulBikeData.csv", locale = locale(encoding = "Windows-1252"))
```
## EDA

```{r}
colSums(is.na(bike_data))
```
No missing values!

```{r}
str(bike_data)
```
```{r}
summary(bike_data)
```
```{r}
unique(bike_data$Seasons)
unique(bike_data$Holiday)
unique(bike_data$`Functioning Day`)
unique(bike_data$Date)
```


```{r}
fixed_bike_data <- bike_data |>
  mutate(
    seasons = as.factor(Seasons),
    holiday = as.factor(Holiday),
    functioning_day = as.factor(`Functioning Day`),
    Date = dmy(Date)
  ) |>
  rename(
    "date" = "Date",
    "rented_bike_count" = "Rented Bike Count",
    "hour" = "Hour",
    "temp_C" = "Temperature(°C)",
    "humidity_per" = "Humidity(%)",
    "wind_speed_mps" = "Wind speed (m/s)",
    "visibility_10m" = "Visibility (10m)",
    "dew_point_temp_C" = "Dew point temperature(°C)",
    "solar_radiation_MJpm2" = "Solar Radiation (MJ/m2)",
    "rainfall_mm" = "Rainfall(mm)",
    "snowfall_cm" = "Snowfall (cm)",
  )
```

```{r}
head(fixed_bike_data)
```

```{r}
fixed_bike_data |>
  summarise(
    n = n(),
    mean = mean(rented_bike_count),
    median = median(rented_bike_count),
    sd = sd(rented_bike_count),
    min = min(rented_bike_count),
    max = max(rented_bike_count),
    q1 = quantile(rented_bike_count, 0.25),
    q3 = quantile(rented_bike_count, 0.75)
  )
```

```{r}
fixed_bike_data |>
  group_by(seasons) |>
  summarise(
    n = n(),
    mean = mean(rented_bike_count),
    median = median(rented_bike_count),
    sd = sd(rented_bike_count),
    min = min(rented_bike_count),
    max = max(rented_bike_count),
    q1 = quantile(rented_bike_count, 0.25),
    q3 = quantile(rented_bike_count, 0.75)
  )
```

```{r}
fixed_bike_data |>
  group_by(holiday) |>
  summarise(
    n = n(),
    mean = mean(rented_bike_count),
    median = median(rented_bike_count),
    sd = sd(rented_bike_count),
    min = min(rented_bike_count),
    max = max(rented_bike_count),
    q1 = quantile(rented_bike_count, 0.25),
    q3 = quantile(rented_bike_count, 0.75)
  )
```

```{r}
fixed_bike_data |>
  group_by(functioning_day) |>
  summarise(
    n = n(),
    mean = mean(rented_bike_count),
    median = median(rented_bike_count),
    sd = sd(rented_bike_count),
    min = min(rented_bike_count),
    max = max(rented_bike_count),
    q1 = quantile(rented_bike_count, 0.25),
    q3 = quantile(rented_bike_count, 0.75)
  )
```

```{r}
fixed_bike_data <- fixed_bike_data |>
  filter(functioning_day == "Yes")
```


```{r}
daily_bike_data <- fixed_bike_data |>
  group_by(date, seasons, holiday) |>
  summarise(
    across(
      .cols = c(rented_bike_count, rainfall_mm, snowfall_cm),
      .fns = sum
    ),
    across(
      .cols = c(temp_C, 
                humidity_per, 
                wind_speed_mps, 
                visibility_10m, 
                solar_radiation_MJpm2,
                dew_point_temp_C),
      .fns = mean
    ),
    .groups = "drop"
  )

daily_bike_data
```

```{r}
summary(daily_bike_data)
```
```{r}
daily_bike_data |>
  summarise(
    n = n(),
    mean = mean(rented_bike_count),
    median = median(rented_bike_count),
    sd = sd(rented_bike_count),
    min = min(rented_bike_count),
    max = max(rented_bike_count),
    q1 = quantile(rented_bike_count, 0.25),
    q3 = quantile(rented_bike_count, 0.75)
  )
```

```{r}
daily_bike_data |>
  group_by(seasons) |>
  summarise(
    n = n(),
    mean = mean(rented_bike_count),
    median = median(rented_bike_count),
    sd = sd(rented_bike_count),
    min = min(rented_bike_count),
    max = max(rented_bike_count),
    q1 = quantile(rented_bike_count, 0.25),
    q3 = quantile(rented_bike_count, 0.75)
  )
```

```{r}
daily_bike_data |>
  group_by(holiday) |>
  summarise(
    n = n(),
    mean = mean(rented_bike_count),
    median = median(rented_bike_count),
    sd = sd(rented_bike_count),
    min = min(rented_bike_count),
    max = max(rented_bike_count),
    q1 = quantile(rented_bike_count, 0.25),
    q3 = quantile(rented_bike_count, 0.75)
  )
```

```{r}
daily_bike_data |>
  select(where(is.numeric)) |>
  cor(use = "complete.obs")
```
```{r}
library(ggplot2)

ggplot(daily_bike_data, aes(x = seasons, y = rented_bike_count, fill = seasons)) +
  geom_boxplot() +
  labs(
    title = "Daily Bike Rentals by Season",
    x = "Season",
    y = "Daily Bike Count"
  ) +
  theme_minimal()
```

```{r}
ggplot(daily_bike_data, aes(x = holiday, y = rented_bike_count, fill = holiday)) +
  geom_boxplot() +
  labs(
    title = "Daily Bike Rentals on Holidays vs Non-Holidays",
    x = "Holiday",
    y = "Daily Bike Count"
  ) +
  theme_minimal()
```

```{r}
ggplot(daily_bike_data, aes(x = temp_C, y = rented_bike_count)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    title = "Daily Bike Rentals vs Temperature",
    x = "Average Temperature",
    y = "Daily Bike Count"
  ) +
  theme_minimal()
```

```{r}
ggplot(daily_bike_data, aes(x = humidity_per, y = rented_bike_count)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm") +
  labs(
    title = "Daily Bike Rentals vs Humidity",
    x = "Average Humidity",
    y = "Daily Bike Count"
  ) +
  theme_minimal()
```

```{r}
daily_bike_data |>
  filter(rainfall_mm > 0) |>
  ggplot(aes(x = rainfall_mm, y = rented_bike_count, color = seasons)) +
  geom_point() +
  labs(
    title = "Bike Rentals on Rainy",
    x = "Rain (mm)",
    y = "Daily Bike Count"
  ) +
  theme_minimal()
```


## Splitting the Data

```{r}
set.seed(123)
bike_split <- initial_split(daily_bike_data, prop = 0.75, strata = seasons)
bike_train <- training(bike_split)
bike_test <- testing(bike_split)
bike_10_fold <- vfold_cv(bike_train, 10)
```

## Fitting MLR Models

```{r}
head(daily_bike_data)
```


```{r}
recipe1 <- recipe(rented_bike_count ~ ., data = daily_bike_data) |>
  step_date(date, features = c("dow")) |>
  step_mutate(
    day_type = factor(if_else(
      date_dow %in% c("Sat", "Sun"),
      "Weekend",
      "Weekday"
    ))
  ) |>
  step_rm(date, date_dow) |>
  step_normalize(all_numeric_predictors(), -all_outcomes()) |>
  step_dummy(seasons, holiday, day_type)
```

```{r}
recipe1 |> prep() |> bake(new_data = NULL) |> names()
```


```{r}
recipe2 <- recipe(rented_bike_count ~ ., data = daily_bike_data) |>
  step_date(date, features = "dow") |>
  step_mutate(
    day_type = factor(if_else(
      date_dow %in% c("Sat", "Sun"),
      "Weekend",
      "Weekday"
    ))
  ) |>
  step_rm(date, date_dow) |>
  step_normalize(all_numeric_predictors(), -all_outcomes()) |>
  step_dummy(all_nominal_predictors()) |>
  step_interact(
    terms = ~ starts_with("holiday"):starts_with("seasons")
  ) |>
  step_interact(
    terms = ~ starts_with("seasons"):temp_C
  ) |>
  step_interact(
    terms = ~ temp_C:rainfall_mm
  )
```


```{r}
recipe2 |> prep() |> bake(new_data = NULL) |> names()
```

```{r}
recipe3 <- recipe(rented_bike_count ~ ., data = daily_bike_data) |>
  step_date(date, features = "dow") |>
  step_mutate(
    day_type = factor(if_else(
      date_dow %in% c("Sat", "Sun"),
      "Weekend",
      "Weekday"
    ))
  ) |>
  step_rm(date, date_dow) |>
  step_dummy(all_nominal_predictors()) |>
  step_interact(
    terms = ~ starts_with("holiday"):starts_with("seasons")
  ) |>
  step_interact(
    terms = ~ starts_with("seasons"):temp_C
  ) |>
  step_interact(
    terms = ~ temp_C:rainfall_mm
  ) |>
  step_poly(
      c(temp_C, humidity_per, wind_speed_mps, visibility_10m,
      solar_radiation_MJpm2, rainfall_mm, snowfall_cm),
    degree = 2
  ) |>
  step_normalize(all_numeric_predictors(), -all_outcomes())

```

```{r}
recipe3 |> prep() |> bake(new_data = NULL) |> names()
```


```{r}
lm_model <- linear_reg() |>
  set_engine("lm")
```

```{r}
workflow1 <- workflow() |>
  add_model(lm_model) |>
  add_recipe(recipe1)

workflow2 <- workflow() |>
  add_model(lm_model) |>
  add_recipe(recipe2)

workflow3 <- workflow() |>
  add_model(lm_model) |>
  add_recipe(recipe3)
```


```{r}
fit1 <- workflow1 |>
  fit_resamples(bike_10_fold)

fit2 <- workflow2 |>
  fit_resamples(bike_10_fold)

fit3 <- workflow3 |>
  fit_resamples(bike_10_fold)
```

```{r}
rbind(collect_metrics(fit1),
      collect_metrics(fit2),
      collect_metrics(fit3)
)
```


```{r}
workflow3 |>
  last_fit(bike_split) |>
  collect_metrics()
```

```{r}
final_coefficients <- workflow3 |>
  last_fit(bike_split) |>
  extract_fit_parsnip() |>
  tidy()

final_coefficients
```


```{r}
final_workflow_2 <- workflow() |>
  add_model(lm_model) |>
  add_recipe(recipe2)

final_fit_2 <- last_fit(
  final_workflow_2,
  split = bike_split,
  metrics = metric_set(rmse, rsq, mae)
)

collect_metrics(final_fit_2)
```

```{r}
final_coefficients_2 <- final_fit_2 |>
  extract_fit_parsnip() |>
  tidy()

final_coefficients_2
```


